# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-10 04:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estPrice', models.FloatField()),
                ('name', models.CharField(max_length=30)),
                ('discount', models.FloatField(default=1.0)),
                ('like', models.IntegerField(default=5)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='DishMat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(max_length=30)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Dish')),
            ],
        ),
        migrations.CreateModel(
            name='DishPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='~/cokassis/image')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Dish')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('breed', models.CharField(max_length=30)),
                ('alias', models.CharField(max_length=30, null=True)),
                ('dish', models.ManyToManyField(through='food.DishMat', to='food.Dish')),
            ],
        ),
        migrations.CreateModel(
            name='WeightInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervalMaxWeight', models.FloatField()),
                ('intervalMinWeight', models.FloatField()),
                ('intervalNote', models.CharField(max_length=30)),
                ('unit', models.CharField(max_length=30)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Material')),
            ],
        ),
        migrations.AddField(
            model_name='dishmat',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Material'),
        ),
        migrations.AddField(
            model_name='dishmat',
            name='supplier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='supplier.Supplier'),
        ),
        migrations.AddField(
            model_name='dishmat',
            name='weightInterval',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='food.WeightInterval'),
        ),
    ]
